// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import FormController from "./form_controller";
application.register("form", FormController);

import PlayerListSyncController from "./player_list_sync_controller";
application.register("player-list-sync", PlayerListSyncController);

import SelectController from "./select_controller";
application.register("select", SelectController);

import Dropdown from "stimulus-dropdown";
application.register("dropdown", Dropdown);
